//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture created successfully.
        /// </summary>
        internal static string CAPTURE_CREATED {
            get {
                return ResourceManager.GetString("CAPTURE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should not be empty!.
        /// </summary>
        internal static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Session.
        /// </summary>
        internal static string OpenSession {
            get {
                return ResourceManager.GetString("OpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1},{2},{3}.
        /// </summary>
        internal static string RectSerializationFormat {
            get {
                return ResourceManager.GetString("RectSerializationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Session.
        /// </summary>
        internal static string SaveSession {
            get {
                return ResourceManager.GetString("SaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Session As....
        /// </summary>
        internal static string SaveSessionAs {
            get {
                return ResourceManager.GetString("SaveSessionAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Trial As....
        /// </summary>
        internal static string SaveTrialAs {
            get {
                return ResourceManager.GetString("SaveTrialAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Files | *.ses.
        /// </summary>
        internal static string SessionFileFilter {
            get {
                return ResourceManager.GetString("SessionFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session: {0} ( {1} trials).
        /// </summary>
        internal static string SessionNodePattern {
            get {
                return ResourceManager.GetString("SessionNodePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Files | *.txt.
        /// </summary>
        internal static string TrialFileFilter {
            get {
                return ResourceManager.GetString("TrialFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial: {0} ({1} templates).
        /// </summary>
        internal static string TrialNodePattern {
            get {
                return ResourceManager.GetString("TrialNodePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string UNTITLED {
            get {
                return ResourceManager.GetString("UNTITLED", resourceCulture);
            }
        }
    }
}
